apiVersion: v1
kind: Service
metadata:
  name: {{ include "debenstack-profile.fullname" . }}
  labels:
    {{- include "debenstack-profile.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.port | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "debenstack-profile.selectorLabels" . | nindent 4 }}
