name: 'Build And Publish Latest'
on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-publish-latest:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Login to Container Registery
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.CLASSIC_GITHUB_TOKEN }}

        - name: Extract medata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v4.3.0
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v4.0.0
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
